# Generated by Django 4.0 on 2022-03-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_consumption', models.IntegerField()),
                ('calories_burnt', models.IntegerField()),
            ],
        ),
    ]
