# Generated by Django 4.0 on 2022-03-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaldata',
            options={'verbose_name_plural': 'General Data'},
        ),
    ]
